baseURL                          = "http://localhost:1337"   # Your domain name. Must end with "/"
theme                            = "inate-hugo"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites

[params]
    themeStyle                   = "auto"                  # Choose "light" or "dark" or "auto"
    favicon                      = "favicon.ico"           # Path to favicon file
    showMenu                     = true                    # Show navigation menu
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "youremail@email.com"   # E-mail address for contact section
    customCSS                    = ["custom.css"]          # Include custom css files placed under assets/
    customJS                     = ["slate.js"]            # Include custom JavaScript files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "medium"            # Input either "medium" or "large" or "fullheight"
        showLatest               = false                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = true                    # show all posts in an archive format
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = false                    # Show your current local time in contact section
        timeZone                 = "Europe/London"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-GB"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        pinterest                = true

    # cookies
    [params.cookies]
        enable = true
        expire_days = 2

    # To enable giscus, the GitHub-discussions-based comment section,
    # input the repository for the discussions below. For more details, see
    # https://www.joelnitta.com/posts/2021-11-24_using-giscus/
    # and https://github.com/giscus/giscus
    [params.giscus]
        # repo = "github-user/github-repo" # Entering repo will enable giscus
        repo-id = "enter-repo-id"
        category = "Comments"
        category-id = "enter-category-id"
        mapping = "pathname"
        reactions-enabled = "1"
        emit-metadata = "0"
        theme = "light"
        lang = "en"

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    #[[params.social]]
    #    url   = "https://facebook.com/"
    #    icon  = "facebook-f" # icon name without the 'fa-'
    #    icon_pack = "fab"
    #[[params.social]]
    #    url   = "https://linkedin.com/"
    #    icon  = "linkedin-in" # icon name without the 'fa-'
    #    icon_pack = "fab"
    #[[params.social]]
    #    url = "mailto:youremail@email.com"  # For a direct email link, use "mailto:test@example.org".
    #    icon = "paper-plane" # icon name without the 'fa-'
    #    icon_pack = "fas"
    [[params.social]]
        url   = "https://hcommons.social/@copim"
        name  = "Mastodon"
        icon  = "mastodon" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = "rel=\"me\"" # Add rel attribute for Mastodon profile link verification
    [[params.social]]
        url   = "https://www.linkedin.com/company/copim/"
        name  = "LinkedIn"
        icon  = "linkedin" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://twitter.com/Copim_community"
        name  = "X"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "x"
    #[[params.social]]
    #    url   = "https://github.com/COPIM"
    #    icon  = "github" # icon name without the 'fa-'
    #    icon_pack = "fab"
    [[params.social]]
        url   = "https://en.wikipedia.org/wiki/COPIM"
        name  = "Wikipedia"
        icon  = "wikipedia-w" # icon name without the 'fa-'
        icon_pack = "fab"

[[ params.nav ]]
name = "projects"
tag = "projects"
icon = "tasks"

[[ params.nav ]]
name = "initiatives"
tag = "initiatives"
icon = "sitemap"

[[ params.nav ]]
name = "resources"
tag = "resources"
icon = "folder-open"

[[ params.nav ]]
name = "documentation"
tag = "documentation"
icon = "file-text"

[[ params.nav ]]
name = "software"
tag = "software"
icon = "code"

[[ params.nav ]]
name = "people"
tag = "people"
icon = "users"

# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    # noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "solarized-dark"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-GB"
        contentDir       = "content/en"
        weight           = 0
        title            = "Copim"
        [languages.en.params]
            description  = "Copim is an international partnership of researchers, universities, librarians, open access book publishers and infrastructure providers. It is building community-owned, open systems and infrastructures to enable open access book publishing to flourish."   # Max 160 characters show in search results
            footerText   = "© 2023 Copim and licensed under a [Creative Commons Attribution 4.0 International License (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)."                      # Text to override default footer text (markdown allowed)

    [languages.es]
        languageName     = "español"
        languageCode     = "es"
        contentDir       = "content/es"
        weight           = 1
        title            = "Copim"
        [languages.es.params]
            description  = "Copim es una asociación internacional de investigadores, universidades, bibliotecarios, editores de libros de acceso abierto y proveedores de infraestructura. Está construyendo sistemas e infraestructuras de propiedad de la comunidad para que pueda prosperar la publicación de libros de acceso abierto."
            footerText   = "© 2023 Copim and licensed under a [Creative Commons Attribution 4.0 International License (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)."

    [languages.de]
        languageName     = "Deutsch"
        languageCode     = "de"
        contentDir       = "content/de"
        weight           = 2
        title            = "Copim"
        [languages.de.params]
            description  = "Copim ist eine internationale Partnerschaft von Forschern, Universitäten, Bibliothekaren, Open-Access-Buch-Verlag und Infrastrukturanbietern. Es baut gemeinschaftseigene, offene Systeme und Infrastrukturen auf, um Open-Access-Book-Publishing zu blühen."
            footerText   = "© 2023 Copim und lizenziert unter einer [Creative Commons Attribution 4.0 International License (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)."

    [languages.fr]
        languageName     = "français"
        languageCode     = "fr"
        contentDir       = "content/fr"
        weight           = 3
        title            = "Copim"
        [languages.fr.params]
            description  = "Copim est un partenariat international de chercheurs, d'universités, de bibliothécaires, d'éditeurs de livres d'accès ouvert et de fournisseurs d'infrastructure. Il construit des systèmes et des infrastructures communautaires et ouverts pour permettre à la publication de livres d'accès ouvert de prospérer."
            footerText   = "© 2023 Copim et sous licence [Créative Commons Attribution 4.0 International License (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)."

    [languages.eo]
        languageName     = "esperanto"
        languageCode     = "eo"
        contentDir       = "content/eo"
        weight           = 4
        title            = "Copim"
        [languages.eo.params]
            description  = "Copim estas internacia partnereco de esploristoj, universitatoj, bibliotekistoj, malfermaj alirlibroeldonistoj kaj infrastrukturprovizantoj. Ĝi konstruas komunum-posedatajn, malfermajn sistemojn kaj infrastrukturojn por ebligi senkaŝan alirlibroeldonadon por prosperi."
            footerText   = "© 2023 Copim kaj licencita sub [Creative Commons Attribution 4.0 International License (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)."
